dist: trusty
sudo: false
language: node_js
node_js:
  - "6"
os:
  - linux
cache: yarn
env: 
  - FIREFOX_VERSION="latest"
  - FIREFOX_VERSION="59.0.2"

before_install:
  # Install firefox for testing.
  - echo $FIREFOX_VERSION
  - export FIREFOX_SOURCE_URL='https://download.mozilla.org/?product=firefox-'$FIREFOX_VERSION'&lang=en-US&os=linux64'
  - wget --no-verbose -O /tmp/firefox-$FIREFOX_VERSION.tar.bz2 $FIREFOX_SOURCE_URL
  - mkdir /tmp/firefox-$FIREFOX_VERSION
  - tar -xvf /tmp/firefox-$FIREFOX_VERSION.tar.bz2 -C /tmp/firefox-$FIREFOX_VERSION
  - export PATH=/tmp/firefox-$FIREFOX_VERSION/firefox:$PATH 
  # Use a virtual display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Install latest chrome.
  - export CHROME_BIN=/usr/bin/google-chrome
  # Use newer Yarn version
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation google-chrome-stable
install:
  - yarn install
script:
  - npm run lint
  - firefox --version
  - npm run test:once
  - npm run integration
  - npm run coverage

# deployment
after_success:
  - cd dist/
deploy:
  skip_cleanup: true # stay in working dir (dist/)
  provider: npm
  email: service.eng@akquinet.de
  api_key:
    secure: "lXfX8LlEBYMSoeSf89Zm6IBk07oOIe/oMcUqtgpyJGoedkP6XrMmKOMzru8LNgG3Nd4UBYFyYSaf4kWJxxMCWe880MWOfjOwxCzDEcErBWm5xBL25EIrt2RguttSNnYvPPBtq+glYSdW2FQDgTgE6ZUV4ELj2XkFGvnPTn6LtYm3R11C5t8fdRuG22t7VB0B1S6pKPMUpM5gQX/1777zNs0OVWLy7xFgvQeAh0Yr7t6V884H6o5Uyo9TMHDZaF3y1tTVtND2sj9iONEEyrDBELYWesEAgZmrwML8k+DOm0sTqJ5mFlCI83731p4FHVWbARaqP9hBcL8v/lLQ5Qu++MRi5bEC93bO4AnH1CwZTReLWpWGq/MxrhImbLE07i3zgk3/3iXMaywdIuFxUJEVMcuATpNMT+le6557s5PW/uQrul1jQaQtgw45yv76TV2jYbjOkq7vTBTOEpj0OJzR7LPZUkG1slaK7RqJ1YzFlTXOwCKk4vSjnKIst04k0h+NmH6jAZtSvJrVtq41mIQeyslRnlTstHarfbf/ZuJOCvpP/KNnvXJ3XWPuDODlbfptMJrnGiBpUniHlMFCYwlBVnaJPzvwv2YOy+Gk3meykuUHanrxiQAVmfqQhcVjKYCOoQebdwWTdzmnMbpzmJ4Qev0RhRRtXMu7GF/DLdKXxQU="
  on:
    condition: "$FIREFOX_VERSION = latest"
    tags: true
    repo: test-editor/web-workspace-navigator
    node: "6"
