dist: trusty
sudo: false
language: node_js
node_js:
  - "6"
cache: yarn
os:
  - linux
before_install:
  # Use a virtual display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Install latest chrome.
  - export CHROME_BIN=chromium-browser
install:
  - yarn install
script:
  - npm run lint
  - npm run build
  - npm run test:once
  # TODO: integration:aot is failing as angular complains about the metadata
  - cd integration && yarn install; cd ..
  - npm run integration:jit
  - npm run coverage