dist: trusty
sudo: false
language: node_js
node_js:
  - "6"
os:
  - linux
cache: yarn
env: 
  - FIREFOX_VERSION="latest"
  - FIREFOX_VERSION="59.0.2"

before_install:
  # Install firefox for testing.
  - echo $FIREFOX_VERSION
  - export FIREFOX_SOURCE_URL='https://download.mozilla.org/?product=firefox-'$FIREFOX_VERSION'&lang=en-US&os=linux64'
  - wget --no-verbose -O /tmp/firefox-$FIREFOX_VERSION.tar.bz2 $FIREFOX_SOURCE_URL
  - mkdir /tmp/firefox-$FIREFOX_VERSION
  - tar -xvf /tmp/firefox-$FIREFOX_VERSION.tar.bz2 -C /tmp/firefox-$FIREFOX_VERSION
  - export PATH=/tmp/firefox-$FIREFOX_VERSION/firefox:$PATH 
  # Use a virtual display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Install latest chrome.
  - export CHROME_BIN=/usr/bin/google-chrome
  # Use newer Yarn version
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation google-chrome-stable
install:
  - yarn install
script:
  - npm run lint
  - firefox --version
  - npm run test:once
  - npm run integration
  - npm run coverage

# deployment
after_success:
  - cd dist/
deploy:
  skip_cleanup: true # stay in working dir (dist/)
  provider: npm
  email: service.eng@akquinet.de
  api_key:
    secure: "iJheeaF+3S73ljLCj9bnbyJy8iNNewTiFmSjMab3bZqu/o6BtEbP0pgXu92+BPE1hhwiFQwROO24H5cZ/F25/u1mBb+VP913wf1U4KEKLNPIgd4WTcCmYDoKhnrU/NjoFGiqqg5zOwd+lrbtqYfn/zqRjVQQR2J4skclouaSyVPF3dBprBST3Tso0hdotBbN5U02FAiCVOu12hrciaW+d1EZpPxnvG2cXJlE5z8C7IUNEGYRSxZXXNbjkWCISBzc+68jlza9SF3wf8McDkEeKLAOPqslIlRORjX4tyUehltSdhH3RPE4M54s7WP97UMcKf8/M4YPVLeK9hH0koimAEA5p7YhZt0Xb4vbSPvN9C/ywzJDs3bIXbFoEcDiaq5zgHlt8L6MaKoq+5AdB0yp1vmpDTFI+WVfOJ18on28BODVZm0BALqdgkJkn/C+3s/MpIaTFsCtdmKLJu0vFiQmlEpmSvddZBD0qd8Wvp2kVWHXrSeNIDIv9JoD5JvSXTDe7Zj0ia+QH+pcDj63WguGrFoKjBR+fsUArD6F7ANzsyiFOUJomv16wn/3ZF4YcYUGNj5LsjN3TpJk/O/bWqehvdbHdCrDqkUChwY42CQraBGmjYQRirD+qjGydxykTIdZsoFLbjaVTFnN6dxbZLlHzp2aIJGxTkfYtn/jz35gznY="
  on:
    condition: "$FIREFOX_VERSION = latest"
    tags: true
    repo: test-editor/web-workspace-navigator
    node: "6"
